### PR TITLE
Rework timestamp attribute value encoding and decoding.

### PR DESCRIPTION
**Pull request by dmolineus**
As discussed on Mumble I rework the timestamp attribute encoding and decoding.

It also includes the fix for contao-community-alliance/dc-general#39 and is required for contao-community-alliance/dc-general#71.

### CODE REVIEW

**Comment by discordier** [comment]
So why are the unit tests now failing?
Will they fix themselves when contao-community-alliance/dc-general#71 is merged?

**Comment by dmolineus** [comment]
I have to adjust the tests. As discussed on mumble the translation between timestamp and the widget is part of the dc general. The timestamp attribute expects the timestamp instead. At the moment  didn't prepeared the tests for it.

For backwards compatibility the widgetToValue() could be reintroduced for handling string time formats as fallback.

**Comment by discordier** [comment]
Yes, please add the bc layer but mark it accordingly with a comment (compat to dcg pre beta-24 then).
Which PR is needed in the dcg for this then or are all things set in there?

**Comment by dmolineus** [comment]
All fixes are included in here as the events being subscribed are already in use.

Some dcg issues needs this fix to work properly: 
 - https://github.com/contao-community-alliance/dc-general/issues/39
 - https://github.com/contao-community-alliance/dc-general/issues/71 (This issue also requires https://github.com/contao-community-alliance/dc-general/pull/123)

**Comment by dmolineus** [comment]
Okay, i reintroduced the widgetToValue method, fixed the timestamp test and added one for the backend subscriber.

To sum it up:
 - This PR does not need any changes of the dcg
 - This PR have an behaviour changes of the attributes API. valueToWidget does not return a formatted date anymore. Calls outside of the DCG may get broken.
 - valueToWidget still accepts dates as string but this behaviour got documented as deprecated.

**Comment by discordier** [comment]
On a second thought, we can not keep the fixme there as the getFilterOptions is used in the Frontend for filters as well and there is no DCG available then.
I think we should simply remove the "FIXME" and keep it as it is, what do you think?

**Comment by dmolineus** [comment]
In the context of MetaModels I think it's fine to remove the fixme note. The attributes are responsible for doing the rendering.

Thinking of the DCG in general im not happy that the DataProvider is responsible to generate readable values in the `getFilterOptions` method. Suggest to introduce yet another event here.

**Comment by discordier** [comment]
Sounds good, what do you have in mind here?

**Comment by dmolineus** [comment]
I would just fire an event here: https://github.com/contao-community-alliance/dc-general/blob/f8c1281d8ff13baf635236295d4e431d7ab95361/src/ContaoCommunityAlliance/DcGeneral/Panel/DefaultFilterElement.php#L148

```php
$event = new GetReadableFilterOptionsEvent($environment, $propertyName, $options);
$dispatcher->dispatch(...);

$this->arrfilterOptions = $event->getResult() ?: $options;
```

**Comment by discordier** [comment]
And the listener will then do what? You want to move the whole parsing into the handler?
How shall MetaModels handle it then?

**Comment by dmolineus** [comment]
As mentioned above MetaModels would still use the method which is already used because MM get the filter options from the attributes which responsibility is also to render values. 

It's purpose is for the dc general outside of the MM context. Image a filter for a timestamp field. The dataprovider would return options which have the timestamp as label. A listener could parse the date or group by month.

**Pull request merged**
